"""Add Google token fields to user table

Revision ID: edfee49c1313
Revises: ed27e18f43cf
Create Date: 2025-06-21 00:26:43.036759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfee49c1313'
down_revision = 'ed27e18f43cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token_expiry')
        batch_op.drop_column('google_refresh_token')
        batch_op.drop_column('google_access_token')

    # ### end Alembic commands ###
