sub_components:
  _spaces: '\s\u00A0'
  _position: 'position|role|job|opening|opportunity|vacancy|title'
  _application: 'application|candidacy'
  
  _parentheses: '\(\)'
  _brackets: '\[\]'
  _tofor: 'to|for'
  _preposition: 'to|for|at|with|from'
  _thanks: 'thank you|thanks|thanx|thank you so much'
  _about: 'An update about|about|regarding|concerning|in relation to|in reference to|update on|follow-up on|Important information about'

components:
  company_name: '[\w{{_spaces}},{{_parentheses}}]*'
  job_title: '[\d\w{{_spaces}},{{_parentheses}}{{_brackets}}-]*'
  email_company_name: '[\w\s]*'
  position: '(?:{{_position}})'
  preposition: '(?:{{_preposition}})'
  tofor: '(?:{{_tofor}})'
  application: '(?:{{_application}})'
  thanks: '(?:{{_thanks}})'
  about: '(?:{{_about}})'
  subdomain: '[\w-]+'
  email_user: '[\w\.-]+'
  case_insensitive: '(?i)'

patterns:
  application_patterns:
  - '{{case_insensitive}}{{thanks}} for applying {{tofor}}+ the ({{job_title}}){{position}}+'
  - '{{case_insensitive}}your application {{tofor}}+ the ({{job_title}}){{position}}? at'
  - '{{case_insensitive}}your interest in the ({{job_title}}){{position}}? at'
  - '{{case_insensitive}}apply for the ({{job_title}}){{position}}+\.'
  - '{{case_insensitive}}we have filled the ({{job_title}}){{position}}+'
  - '{{case_insensitive}}consider you for ({{job_title}})\.'
  - '{{case_insensitive}}for our ({{job_title}}){{position}}+\.'
  - '{{case_insensitive}}apply and engage with us about the ({{job_title}}){{position}}+\.'
  - '{{case_insensitive}}overwhelming response to the ({{job_title}}){{position}}+'
  - '{{case_insensitive}}{{thanks}} for your interest in the role of ({{job_title}})\.'
  - '{{case_insensitive}}^{{thanks}} for taking the time to apply (?:to|for) the ({{job_title}}){{position}}+(?: at)?'
  - '{{case_insensitive}}questions you may have about {{company_name}} or the ({{job_title}}){{position}}+'
  - '{{case_insensitive}}reviewed your background and qualifications for the ({{job_title}}){{position}}+\.'

