sub_components:
  spaces: '\s\u00A0'
  position: 'position|role|job|opening|opportunity|vacancy|title'
  application: 'application|candidacy'
  case_insensitive: '(?i)'
  parentheses: '\(\)'
  brackets: '\[\]'
  preposition: 'to|for|at|with|from'
  _thanks: 'thank you|thanks|thanx|thank you so much'
  _about: 'An update about|about|regarding|concerning|in relation to|in reference to|update on|follow-up on|Important information about'

components:
  company_name: '[\w{{spaces}},{{parentheses}}]*'
  job_title: '[\d\w{{spaces}},{{parentheses}}{{brackets}}]*'
  email_company_name: '[\w\s]*'
  position_group: '(?:{{position}})'
  preposition_group: '(?:{{preposition}})'
  application_group: '(?:{{application}})'
  thanks: '(?:{{_thanks}})'
  about: '(?:{{_about}})'
  subdomain: '[\w-]+'
  email_user: '[\w\.-]+'

patterns:
  subject_keywords:
    - '{{case_insensitive}}applied'
    - '{{case_insensitive}}application received'
    - '{{case_insensitive}}{{thanks}} for applying'
    - '{{case_insensitive}}submitted your resume'
    - '{{case_insensitive}}we appreciate your interest'
    - '{{case_insensitive}}{{about}} your application'
    - '{{case_insensitive}}your application for {{job_title}} at'
    - '{{case_insensitive}}{{about}} your candidacy'
    - '{{case_insensitive}}{{thanks}} for applying'
    - '{{case_insensitive}}{{thanks}} for your application'
    - '{{case_insensitive}}application status'
    - '{{case_insensitive}}{{_thanks}} for your interest in [\w\s,]*'
    - '{{case_insensitive}}[\w\s,]* Interview Request'
    - '{{case_insensitive}}Intro call with [\w\s,]*'
    - '{{case_insensitive}}Position Filled'
    - '{{case_insensitive}}[\w\s]*, we''re confirming your [\w\s'']* interview with [\w\s,]*!?'
    - '{{case_insensitive}}your application was sent to'
    - '{{case_insensitive}}Invitation [\w\s,]* Interview'
    - '{{case_insensitive}}{{_thanks}} for your interest in [\w\s,]*'
    - '{{case_insensitive}}Phone Screen Availability'

  body_phrases:
    - '{{case_insensitive}}decided to move forward with other candidates'
    - '{{case_insensitive}}Follow-Up on Your Recent Interview'
    - '{{case_insensitive}}moving forward with your application'
    - '{{case_insensitive}}next steps in the hiring process'
    - '{{case_insensitive}}other applicants whose skills and background more closely'
    - '{{case_insensitive}}Unfortunately, we won''t be moving forward at this time'
    - '{{case_insensitive}}We really appreciate you taking the time to apply'
    - '{{case_insensitive}}We will keep your resume on file'
    - '{{case_insensitive}}we’re excited to consider you'
    - '{{case_insensitive}}we’ve received your application'
    - '{{case_insensitive}}who more closely match our needs at this time'
    - '{{case_insensitive}}your application is under review'
    - '{{case_insensitive}}your interview is scheduled'
    - '{{case_insensitive}}{{about}} your application'
    - '{{case_insensitive}}{{_thanks}} for applying for the'
    - '{{case_insensitive}}{{_thanks}} for applying to our open'
    - '{{case_insensitive}}{{_thanks}} for considering a career opportunity'
    - '{{case_insensitive}}{{_thanks}} for expressing interest in our [\w\s,]* role[!\.]+'
    - '{{case_insensitive}}{{_thanks}} for taking the time to apply'
    - '{{case_insensitive}}{{_thanks}} for taking the time to apply'
    - '{{case_insensitive}}{{_thanks}} for your application'
    - '{{case_insensitive}}{{_thanks}} for your interest in the'
    - '{{case_insensitive}}we recently reviewed your resume'
    - '{{case_insensitive}}before moving forward with the hiring manager'


  sender_patterns:
    - 'no-reply@{{subdomain}}\.jobs'
    - 'noreply@{{subdomain}}\.greenhouse\.io'
    - 'no-reply@{{subdomain}}\.greenhouse-mail\.io'
    - 'do-not-reply@{{subdomain}}\.lever\.co'
    - 'globalhr@{{subdomain}}\.myworkday\.com'
    - 'no-reply@{{subdomain}}\.ashbyhq\.com'
    - 'notifications@app\.bamboohr\.com'
    - 'no-reply@ats\.rippling\.com'
    - '{{email_user}}@myworkday\.com'
    - 'noreply@candidates\.workablemail\.com'

  sender_exclude_patterns:
    - 'chris.thomas@cleaner.codes'

  email_blacklist:
    - '(?!jobs-noreply@)@linkedin\.com'
    - 'jobalert@lensa.com'
    - 'friendupdates@facebookmail.com'
    - 'notification@facebookmail.com'
    - '{{email_user}}@mail.coinbase.com'

  exclude_if_subject_contains:
    - 'advertisement'
    - 'newsletter'
    - 'survey'
    - 'you’re getting paid today'
    - 'Update on your Gusto benefits'
    - 'You can now set beneficiaries'
    - 'You just received'
    - 'Request time off with Gusto'
    - 'Please review your Affordable Care Act'
    - 'Please review your Summary of Health Plan'
    - 'Security Alert:'
    - 'Reset password'
    - 'please add me to your LinkedIn network$'
    - 'start a conversation with your new connection$'
    - 'I just requested to connect$'
    - 'I (?:still )?want to connect$'
    - 'I''d like to connect 👤$'
    - 'I''ve sent you a connection request$'
    - '(?:[\w]*) just messaged you$'
    - '^Message replied: '
    - '^Messages from (:[\w\s\d,]*) are waiting$'
    - 'Password setup'
    - '^Reset your password for your candidate account$'
    - '^View my connection request$'
    - '^You have an invitation(?: ✉️)?$'
    - '^You have \d+ new messages?$'
    - '^Your latest Oracle jobs'
    - '{{case_insensitive}}Password Reset'
    - '{{case_insensitive}}Price alert:''
